### ISSUE TITLE
Null pointer exception on CL style cups.

### ISSUE THREAD

**Issue by NexxusDrako** [NexxusDrako/leagion-scorinator#1]
When scorinationg a CL style cup, Leagion will crash with a null pointer exception. The line it picks out has something to do with the first leg of said cup.

I have yet to fully test, but it is easily reproduceable with the menu, I haven't tested input files yet.

Console Output: http://pastebin.com/EiCRgSTX

**Comment by Rejis** [comment]
The good news is that I have isolated the issue. The bad news is that this seems to have introduced (or unveiled, idk?) an issue with matches going into extra time erronously. Looking at this now...

**Comment by Rejis** [comment]
Works in my branch now.
