### ISSUE TITLE
Offensive/Defensive modifier reversal.

### ISSUE THREAD

**Issue by NexxusDrako** [NexxusDrako/leagion-scorinator#12]
I think this should be an easy one, but I want to gain approval first. Basically, this just entails swapping positive/defensive and negative/offensive around to match modern scorinators such as Xkoranate and NSFS.

If this is approved, I will work on it immediately.

**Comment by NexxusDrako** [comment]
I've had a chat with Rejis over IRC, and we've agreed to not swap the modifiers, as we feel keeping the status quo will set the scorinator apart from the others. Another reason quoted was Rejistanian IC reasons and a personal love for Karela (defense).

**Comment by Rejis** [comment]
This had been a deliberate decision and thus I would like to know the usability impacts but for new users as well as for people who need to adjust their LGN files.

**Comment by NexxusDrako** [comment]
I will set about to try and find this info. I think the interactive mode should at least clearly state this, as the README does. The only reason one would really read the readme is to find out about file input and learn how to use the scorinator. If one is not intrested in such things or does not bother with the readme, then we need to state the reversed modifiers inside the interactive mode, which is what many would probably jump into.
