### ISSUE TITLE
CL style elimination and no draws parameter

### ISSUE THREAD

**Issue by Rejis** [NexxusDrako/leagion-scorinator#2]
Well, you can set these together, but I am unsure how to make tiebreakers which make sense. Previous code was a ball of fail which required excorcism. It was glitchy, it was faily and I wonder whether it ever worked. [5 minute long rant about past me removed.]

So yeah, I implemented a basic away goal rule here, but I am not sure whether something else is required here.

**Comment by NexxusDrako** [comment]
Well, in theory, you may not need to do much more, however, I found something which may be of interest.

Round of 2
A 0 C 0  AET: 0:0  APK: 8:7
C 0 A 0  AET: 1:0

It seems penalty kicks in leg 1 don't count towards the score in leg 2, forcing Extra TIme. I'll be making a seperate bug report for this, but I'm not sure if it's designed that way.

**Comment by Rejis** [comment]
It isn't.

**Comment by NexxusDrako** [comment]
Okay then. Thanks.

**Comment by NexxusDrako** [comment]
Closing as this is put into more detail in Issue #4.
