### ISSUE TITLE
CL Style and nodraws doesn't count penalty kicks.

### ISSUE THREAD

**Issue by NexxusDrako** [NexxusDrako/leagion-scorinator#4]
I have noticed that when running a CL style tournament without draws, Penalties are not counted in the final score. I know they are usually separate, but it may not appear that way to the end user. Therefore, I have tagged this bug and question, as I'm not sure if this is by design or whether it's a bug.

PasteBin: http://pastebin.com/SUW1aQNF

**Comment by Rejis** [comment]
it's a bug.

**Comment by NexxusDrako** [comment]
Alright, I'll take a quick look at the code later on, see how it may work.

**Comment by NexxusDrako** [comment]
Right, I've fixed a minor bug, were the scorination level for invoking the penalty kick away goals was set to 1 instead of 3, thus being impossible to invoke properly, as penalties are level 3 and regular time is level 1. I'm not sure if it's related, I've been trying to test, but getting the correct results is hard. It looked like a bug however, so I've fixed it.

**Comment by Rejis** [comment]
Urgh... yes, if that was in scorinate_match, it can very well have been the cause... but I need to fully look into it when I have time and am conscious.

**Comment by NexxusDrako** [comment]
I believe one of the patches a little while ago that I made has put in a potential fix. Closing until proven wrong.
